spring:
  application:
    name: auth-service
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3308/auth_service
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
    drop-first: false  
    default-schema: auth_service
    liquibase-schema: auth_service
    contexts: dev,prod  
    label-filter: v1.0.0      
    parameters:
      appName: auth-service
      appVersion: 1.0.0

# JWT Configuration
jwt:
  secret: MA9TFJ2cV/PxU1h68mbsq/vZB0LskxuAtsQFyZdrmBCNuGk+1pVS6YFIrQEEmnVV
  expiration: 86400000    # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

# Server Configuration
server:
  port: 8084

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    com.loc.auth_service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
